# Generated by Django 5.0.6 on 2024-05-22 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initiated', models.DateTimeField(auto_created=True)),
                ('reference_no', models.CharField(max_length=255)),
                ('amount', models.FloatField(max_length=255)),
                ('sourceAccount', models.CharField(max_length=255)),
                ('responsePayload', models.TextField()),
                ('callbackPayload', models.TextField()),
                ('url', models.UUIDField()),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initiated', models.DateTimeField(auto_created=True)),
                ('reference_no', models.CharField(max_length=255)),
                ('amount', models.FloatField(max_length=255)),
                ('destinationAccount', models.CharField(max_length=255)),
                ('responsePayload', models.TextField()),
                ('callbackPayload', models.TextField()),
                ('url', models.UUIDField()),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
