# Generated by Django 4.0.1 on 2024-05-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payin',
            name='type',
            field=models.CharField(default='TRANSFER', max_length=255),
        ),
        migrations.AddField(
            model_name='payout',
            name='type',
            field=models.CharField(default='TRANSFER', max_length=255),
        ),
        migrations.AlterField(
            model_name='payin',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
