# Generated by Django 4.0.1 on 2024-06-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payin_type_payout_type_alter_payin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payin',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
