# Generated by Django 4.0.1 on 2024-06-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payin_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='channel',
            field=models.CharField(default='MPESA', max_length=255),
            preserve_default=False,
        ),
    ]
