# Generated by Django 4.0.1 on 2024-06-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payout_destinationaccount_payin_meta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payin',
            old_name='sourceAccount',
            new_name='source_account',
        ),
    ]
