# Generated by Django 4.0.1 on 2024-06-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_sourceaccount_payin_source_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payin',
            name='date_initiated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
