# Generated by Django 4.0.1 on 2024-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payin_date_initiated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='date_initiated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
