# Generated by Django 4.0.1 on 2024-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payout_payin_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
