# Generated by Django 4.0.1 on 2024-06-18 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payout_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payout',
            name='date_initiated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
