# Generated by Django 4.0.1 on 2024-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_payout_timestamp_alter_payout_date_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='message',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
