# Generated by Django 5.0.6 on 2024-05-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_id_type_user_selfie_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
