# Generated by Django 5.0.6 on 2024-05-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_secondary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
