# Generated by Django 4.0.1 on 2024-06-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_groups_alter_user_id_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money_on_airtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='money_on_buy_goods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='money_on_paybill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='money_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_money_spent',
            field=models.IntegerField(default=0),
        ),
    ]
